=== Mimi-Siku/XMLMaster/master.dtd
<?xml version="1.0" encoding="utf-8" ?>

<!ELEMENT master (enseignant+, UE+, parcours+)>
<!ELEMENT enseignant (nom, adrElec, adrSite)>
<!ELEMENT UE (nom, ref-responsable, nbCredits, resume, plan, lieu)>
<!ELEMENT parcours (nom, ref-responsable, description, debouches?, semestre+)>
<!ELEMENT semestre (bloc+)>
<!ELEMENT bloc (role, ref-UE+)>

<!ELEMENT nom (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT nbCredits (#PCDATA)>
<!ELEMENT resume (#PCDATA)>
<!ELEMENT plan (#PCDATA)>
<!ELEMENT lieu (#PCDATA)>
<!ELEMENT adrElec (#PCDATA)>
<!ELEMENT adrSite (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT debouches (#PCDATA)>
<!ELEMENT role (#PCDATA)>

<!ELEMENT ref-UE (#PCDATA)>
<!ATTLIST ref-UE
	ref IDREF #REQUIRED
	>
<!ELEMENT ref-responsable (#PCDATA)>
<!ATTLIST ref-responsable
	ref IDREF #REQUIRED
	>

<!ATTLIST enseignant
	id ID #IMPLIED
	>
<!ATTLIST UE
	id ID #IMPLIED
	>
<!ATTLIST parcours
	id ID #IMPLIED
	>

=== Mimi-Siku/XMLMaster/master.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE master SYSTEM "master.dtd">

<master
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="master.xsd"
		>

	<enseignant id="ENS-0">
		<nom>Roland AGOPIAN</nom>
		<adrElec>roland.agopian@univ-amu.fr</adrElec>
		<adrSite>Luminy</adrSite>
	</enseignant>
	<enseignant id="ENS-1">
		<nom>Thierry ARTIÈRES</nom>
		<adrElec>thierry.artieres@lif.univ-mrs.fr</adrElec>
		<adrSite>Saint-Jérôme</adrSite>
	</enseignant>
	<enseignant id="ENS-2">
		<nom>Frederic BECHET</nom>
		<adrElec>frederic.bechet@univ-amu.fr</adrElec>
		<adrSite>Saint-Jérôme</adrSite>
	</enseignant>
	<enseignant id="ENS-3">
		<nom>Clara BERTOLISSI</nom>
		<adrElec>clara.bertolissi@univ-amu.fr</adrElec>
		<adrSite>Saint-Jérôme</adrSite>
	</enseignant>
	<enseignant id="ENS-4">
		<nom>Omar BOUCELMA</nom>
		<adrElec>omar.boucelma@univ-amu.fr</adrElec>
		<adrSite>Saint-Jérôme</adrSite>
	</enseignant>
	<enseignant id="ENS-5">
		<nom>Martine BROCHE</nom>
		<adrElec>martine.broche@univ-amu.fr</adrElec>
		<adrSite>Saint-Jérôme</adrSite>
	</enseignant>
	<enseignant id="ENS-6">
		<nom>Nadia CREIGNOU</nom>
		<adrElec>nadia.creignou@univ-amu.fr</adrElec>
		<adrSite>Saint-Jérôme</adrSite>
	</enseignant>
	<enseignant id="ENS-7">
		<nom>Rémi MORIN</nom>
		<adrElec>remi.morin@univ-amu.fr@univ-amu.fr</adrElec>
		<adrSite>Saint-Jérôme</adrSite>
	</enseignant>
	<enseignant id="ENS-8">
		<nom>Jean-Luc MASSAT</nom>
		<adrElec>jean-luc.massat@univ-amu.fr</adrElec>
		<adrSite>Saint-Jérôme</adrSite>
	</enseignant>
	<enseignant id="ENS-9">
		<nom>Emmanuel GODARD</nom>
		<adrElec>emmanuel.godard@univ-amu.fr</adrElec>
		<adrSite>Saint-Jérôme</adrSite>
	</enseignant>


  <UE id="UE-0">
    <nom>Génie Logiciel</nom>
		<ref-responsable ref="ENS-1"/>
    <nbCredits>6</nbCredits>
    <resume>
      <![CDATA[
        Processus logiciel
        Gestion de projet
        Spécification et conception (artefact : notation UML)
        Design patterns
      ]]>
    </resume>
    <plan>20h/20h/20h</plan>
    <lieu>Luminy</lieu>
  </UE>

  <UE id="UE-1">
		<nom>Complexité</nom>
		<ref-responsable ref="ENS-1"/>
    <nbCredits>6</nbCredits>
    <resume>
      <![CDATA[
        Processus logiciel
        Gestion de projet
        Spécification et conception (artefact : notation UML)
        Design patterns
      ]]>
    </resume>
    <plan>20h/20h/20h</plan>
    <lieu>Saint-Jérôme</lieu>
  </UE>

  <UE id="UE-2">
		<nom>Réseaux</nom>
		<ref-responsable ref="ENS-1"/>
    <nbCredits>6</nbCredits>
    <resume>
      <![CDATA[
        Processus logiciel
        Gestion de projet
        Spécification et conception (artefact : notation UML)
        Design patterns
      ]]>
    </resume>
    <plan>20h/20h/20h</plan>
    <lieu>Saint-Jérôme</lieu>
  </UE>

  <UE id="UE-3">
		<nom>Programmation fonctionnelle</nom>
		<ref-responsable ref="ENS-1"/>
    <nbCredits>3</nbCredits>
    <resume>
      <![CDATA[
        Processus logiciel
        Gestion de projet
        Spécification et conception (artefact : notation UML)
        Design patterns
      ]]>
    </resume>
    <plan>20h/20h/20h</plan>
    <lieu>Saint-Jérôme</lieu>
  </UE>

  <UE id="UE-4">
		<nom>BDR : approfondissement</nom>
		<ref-responsable ref="ENS-1"/>
    <nbCredits>3</nbCredits>
    <resume>
      <![CDATA[
        Processus logiciel
        Gestion de projet
        Spécification et conception (artefact : notation UML)
        Design patterns
      ]]>
    </resume>
    <plan>20h/20h/20h</plan>
    <lieu>Saint-Jérôme</lieu>
  </UE>

  <UE id="UE-5">
		<nom>Programmation logique</nom>
		<ref-responsable ref="ENS-1"/>
    <nbCredits>3</nbCredits>
    <resume>
      <![CDATA[
        Processus logiciel
        Gestion de projet
        Spécification et conception (artefact : notation UML)
        Design patterns
      ]]>
    </resume>
    <plan>20h/20h/20h</plan>
    <lieu>Saint-Jérôme</lieu>
  </UE>

  <UE id="UE-6">
		<nom>Outils de l'internet</nom>
		<ref-responsable ref="ENS-1"/>
    <nbCredits>3</nbCredits>
    <resume>
      <![CDATA[
        Processus logiciel
        Gestion de projet
        Spécification et conception (artefact : notation UML)
        Design patterns
      ]]>
    </resume>
    <plan>20h/20h/20h</plan>
    <lieu>Saint-Jérôme</lieu>
  </UE>

  <UE id="UE-7">
		<nom>Système embarqué</nom>
		<ref-responsable ref="ENS-1"/>
    <nbCredits>3</nbCredits>
    <resume>
      <![CDATA[
        Processus logiciel
        Gestion de projet
        Spécification et conception (artefact : notation UML)
        Design patterns
      ]]>
    </resume>
    <plan>20h/20h/20h</plan>
    <lieu>Saint-Jérôme</lieu>
  </UE>

  <UE id="UE-8">
		<nom>Système embarqué</nom>
		<ref-responsable ref="ENS-1"/>
    <nbCredits>3</nbCredits>
    <resume>
      <![CDATA[
        Processus logiciel
        Gestion de projet
        Spécification et conception (artefact : notation UML)
        Design patterns
      ]]>
    </resume>
    <plan>20h/20h/20h</plan>
    <lieu>Saint-Jérôme</lieu>
  </UE>

  <UE id="UE-9">
		<nom>Modèles à évènements discrets</nom>
		<ref-responsable ref="ENS-1"/>
    <nbCredits>3</nbCredits>
    <resume>
      <![CDATA[
        Processus logiciel
        Gestion de projet
        Spécification et conception (artefact : notation UML)
        Design patterns
      ]]>
    </resume>
    <plan>20h/20h/20h</plan>
    <lieu>Saint-Jérôme</lieu>
  </UE>

  <UE id="UE-10">
		<nom>Pratique de la cryptographie</nom>
		<ref-responsable ref="ENS-1"/>
    <nbCredits>3</nbCredits>
    <resume>
      <![CDATA[
        Processus logiciel
        Gestion de projet
        Spécification et conception (artefact : notation UML)
        Design patterns
      ]]>
    </resume>
    <plan>20h/20h/20h</plan>
    <lieu>Saint-Jérôme</lieu>
  </UE>

  <UE id="UE-11">
		<nom>Anglais</nom>
		<ref-responsable ref="ENS-1"/>
    <nbCredits>3</nbCredits>
    <resume>
      <![CDATA[
        Processus logiciel
        Gestion de projet
        Spécification et conception (artefact : notation UML)
        Design patterns
      ]]>
    </resume>
    <plan>20h/20h/20h</plan>
    <lieu>Saint-Jérôme</lieu>
  </UE>

  <UE id="UE-12">
		<nom>Communication</nom>
		<ref-responsable ref="ENS-1"/>
    <nbCredits>3</nbCredits>
    <resume>
      <![CDATA[
        Processus logiciel
        Gestion de projet
        Spécification et conception (artefact : notation UML)
        Design patterns
      ]]>
    </resume>
    <plan>20h/20h/20h</plan>
    <lieu>Saint-Jérôme</lieu>
  </UE>

  <UE id="UE-13">
		<nom>XML</nom>
		<ref-responsable ref="ENS-1"/>
    <nbCredits>3</nbCredits>
    <resume>
      <![CDATA[
        Processus logiciel
        Gestion de projet
        Spécification et conception (artefact : notation UML)
        Design patterns
      ]]>
    </resume>
    <plan>20h/20h/20h</plan>
    <lieu>Saint-Jérôme</lieu>
  </UE>

  <UE id="UE-14">
		<nom>Algorithmique et recherche opérationnelle</nom>
		<ref-responsable ref="ENS-1"/>
    <nbCredits>3</nbCredits>
    <resume>
      <![CDATA[
        Processus logiciel
        Gestion de projet
        Spécification et conception (artefact : notation UML)
        Design patterns
      ]]>
    </resume>
    <plan>20h/20h/20h</plan>
    <lieu>Saint-Jérôme</lieu>
  </UE>

  <UE id="UE-15">
		<nom>Programmation parallèle</nom>
		<ref-responsable ref="ENS-1"/>
    <nbCredits>3</nbCredits>
    <resume>
      <![CDATA[
        Processus logiciel
        Gestion de projet
        Spécification et conception (artefact : notation UML)
        Design patterns
      ]]>
    </resume>
    <plan>20h/20h/20h</plan>
    <lieu>Saint-Jérôme</lieu>
  </UE>

  <UE id="UE-16">
		<nom>Projet</nom>
		<ref-responsable ref="ENS-1"/>
    <nbCredits>6</nbCredits>
    <resume>
      <![CDATA[
        Processus logiciel
        Gestion de projet
        Spécification et conception (artefact : notation UML)
        Design patterns
      ]]>
    </resume>
    <plan>20h/20h/20h</plan>
    <lieu>Saint-Jérôme</lieu>
  </UE>

  <UE id="UE-17">
		<nom>Stage de deux mois</nom>
		<ref-responsable ref="ENS-1"/>
    <nbCredits>6</nbCredits>
    <resume>
      <![CDATA[
        Processus logiciel
        Gestion de projet
        Spécification et conception (artefact : notation UML)
        Design patterns
      ]]>
    </resume>
    <plan>20h/20h/20h</plan>
    <lieu>Saint-Jérôme</lieu>
  </UE>

  <UE id="UE-18">
		<nom>Sémantique</nom>
		<ref-responsable ref="ENS-1"/>
    <nbCredits>3</nbCredits>
    <resume>
      <![CDATA[
        Processus logiciel
        Gestion de projet
        Spécification et conception (artefact : notation UML)
        Design patterns
      ]]>
    </resume>
    <plan>20h/20h/20h</plan>
    <lieu>Saint-Jérôme</lieu>
  </UE>

  <UE id="UE-19">
		<nom>Algorithmique distribuée</nom>
		<ref-responsable ref="ENS-1"/>
    <nbCredits>3</nbCredits>
    <resume>
      <![CDATA[
        Processus logiciel
        Gestion de projet
        Spécification et conception (artefact : notation UML)
        Design patterns
      ]]>
    </resume>
    <plan>20h/20h/20h</plan>
    <lieu>Saint-Jérôme</lieu>
  </UE>

  <UE id="UE-20">
		<nom>Intégration des systèmes d'informations</nom>
		<ref-responsable ref="ENS-1"/>
    <nbCredits>3</nbCredits>
    <resume>
      <![CDATA[
        Processus logiciel
        Gestion de projet
        Spécification et conception (artefact : notation UML)
        Design patterns
      ]]>
    </resume>
    <plan>20h/20h/20h</plan>
    <lieu>Saint-Jérôme</lieu>
  </UE>

  <UE id="UE-21">
		<nom>Initiation à la fouille de données et à l'optimisation des SGBD</nom>
		<ref-responsable ref="ENS-1"/>
    <nbCredits>3</nbCredits>
    <resume>
      <![CDATA[
        Processus logiciel
        Gestion de projet
        Spécification et conception (artefact : notation UML)
        Design patterns
      ]]>
    </resume>
    <plan>20h/20h/20h</plan>
    <lieu>Saint-Jérôme</lieu>
  </UE>

  <UE id="UE-22">
		<nom>Intelligence artificielle</nom>
